### PR TITLE
Add some hypothesis tests

### PR DESCRIPTION
**Pull request by jimbarrett27**
had a nasty heisenbug in the unit test for filling around a font (where my breakpoints and print statements to find the bug made hypothesis no longer generate failing examples...). I did find and fix a likely candidate for the bug though

### CODE REVIEW

**Comment by jimbarrett27** [comment]
I'm also not sure if the rectangle.py file is the right place for the space filling around a font, or at least I don't think that's the filename I'd expect to find such functions...

**Comment by jimbarrett27** [comment]
the space filling also seems to break down when you have a font size less than 5 pixels, since then for some characters there are no pixels with the same colour as the background. Not really sure this is a problem worth addressing?

**Review by naslundx — APPROVED** [review]

**Comment by naslundx** [comment]
Nah, if there are characters with that sub-5 pixel text, it's not worth writing in between anyway :D

**Comment by naslundx** [comment]
And regarding placement - no, it might make more sense in font.py or even a different file completely, but let's think some more on that

**Pull request merged**
